Update check-submodules.yml

diff --git a/.github/workflows/check-submodules.yml b/.github/workflows/check-submodules.yml
--- a/.github/workflows/check-submodules.yml
+++ b/.github/workflows/check-submodules.yml
@@ -13,7 +13,7 @@ jobs:
         git submodule status flask_back | grep -q '^-' && (echo "Error: flask_back was not updated" && exit 1) || echo "flask_back was updated"
     - name: Check submodule front  
       run: |  
-        git submodule status front | grep -q '^-' && echo "front was updated" || (echo "Error: front was not updated" && exit 1)        
+        git submodule status front | grep -q '^-' && (echo "Error: front was not updated" && exit 1) || echo "front was updated"        
     - name: Fail if any submodule was not updated
       if: failure()
       run: exit 1
